//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bip11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        public int Id { get; set; }
        public int Id_fio { get; set; }
        public int Id_avto { get; set; }
        public System.DateTime Data_take { get; set; }
        public Nullable<int> Data_re { get; set; }
    
        public virtual FIO FIO { get; set; }
        public virtual Avto Avto { get; set; }
    }
}
